# Header
menu:
  Home: /
  Archives: /archives
  More: http://katelhughes.com/

# Logo Image Source
logo_src: /images/logo.svg

# Theme Main Subtitle
subtitle_main: This is Phantom, a free, fully responsive site<br />template designed by <a href="http://html5up.net">HTML5 UP</a>.

# Theme Secondary subtitle
susbtitle_secondary: Etiam quis viverra lorem, in semper lorem. Sed nisl arcu euismod sit amet nisi euismod sed cursus arcu elementum ipsum arcu vivamus quis venenatis orci lorem ipsum et magna feugiat veroeros aliquam. Lorem ipsum dolor sit amet nullam dolore.

# Footer About Section
about_footer: Katie Hughes is a software developer in Oregon who finds programming languages, interior design, and comics rad.

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "https://s-media-cache-ak0.pinimg.com/736x/53/39/3f/53393f5ba1655261b2d9bd9f8b4e8dc5.jpg"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates:

# Comments. Choose one by filling up the information
# comments:
#   # Disqus comments
#   disqus_shortname: klugjo
#   # Facebook comments
#   facebook:
#     appid:
#     comment_count: 5
#     comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: UA-62083781-2

# Social Accounts
twitter_url: https://twitter.com/katieslynnh
instagram_url: https://www.instagram.com/katelhughes/
github_url: https://github.com/hugheskatie
rss_url: \atom.xml
